---
title: "Untitled"
output: github_document
---
[用R绘制情人节礼物](https://cosx.org/2012/02/valentines-gift-by-using-r)

viewport是相当于PS中的图层的概念，使用pushViewport()命令来锁定该图层。

```{r}
# add necessory 
library(grid)
```

```{r, echo=FALSE}
heart<-function(lcolor){
    t=seq(0,2*pi,by=0.1)
    x=16*sin(t)^3
    y=13*cos(t)-5*cos(2*t)-2*cos(3*t)-cos(4*t)
    a=(x-min(x))/(max(x)-min(x))
    b=(y-min(y))/(max(y)-min(y))
    grid.lines(a,b,gp=gpar(col=lcolor,lty="solid",lwd=3))
}

drawHeart<-function(colcor,angle){
    grid.newpage()
    vp<-viewport(0.5,0.5,w=0.8,h=0.8,angle=angle)
    pushViewport(vp)
    heart(colcor)
}
drawHeart("hotpink",0)

#绘制玫瑰花
rose=function(){
    #circle
    grid.circle(x=0.5,y=0.5,r=0.5,gp=gpar(fill="red",lwd=3))
    vp0<-viewport(0.5,0.5,w=0.9,h=0.9)
    pushViewport(vp0)

    #三角形
    grid.polygon(x=c(0.08,0.5,0.94),y=c(0.22,1.03,0.22),gp=gpar(lwd=3))
    vp1<-viewport(0.5,0.5,w=0.4,h=0.4)
    pushViewport(vp1)

    grid.circle(x=0.5,y=0.5,r=0.5,gp=gpar(fill="red",lwd=3))
    vp2<-viewport(0.5,0.5,w=0.9,h=0.9)
    pushViewport(vp2)

    grid.polygon(x=c(0.08,0.5,0.94),y=c(0.22,1.03,0.22),gp=gpar(lwd=3))   
}
#grid.newpage()
#rose()

#嵌套心形
multiHeart<-function(){
    grid.newpage()
    pushViewport(viewport(x = 0.1, y = 0.1, w = 0.2, h = 0.2))
    grid.newpage()
    for (j in 1:25) {
        vp <- viewport(0.5, 0.5, w = 0.9, h = 0.9)
        pushViewport(vp)
        heart("hotpink")
    }
}
multiHeart()

#情人节快乐

grid.newpage()
vp1 <- viewport(0.4, 0.5, w = 0.5, h = 0.5, angle = 15)
pushViewport(vp1)
heart("red")
vp2 <- viewport(1.2, 0.5, w = 1, h = 1, angle = -15)
pushViewport(vp2)
heart("hotpink")
grid.text("Happy valentine's day!", x = 0.2, y = 1.2, just = c("center", "bottom"), 
          gp = gpar(fontsize = 20), vp = vp1)
vp3 <- viewport(-0.65, 1.0, w = 0.3, h = 0.3, angle = -30)
pushViewport(vp3)
rose()
```

